### ISSUE TITLE
Custom configurations

### ISSUE THREAD

**Issue by pedyard** [igor-makarov/xcake#210]
When trying to create a custom configuration with `project.debug_configuration :Test`, I do see this configuration in `project.all_configurations.each`, but not in `target.all_configurations.each`. Besides not having `Test` there, target also still has the implicit configurations `Debug` and `Release`.

Not sure if this is the way it is supposed to be and if so, is there a way I could get the project configurations also as target configurations?

**Comment by igor-makarov** [comment]
Published [0.9.3](https://rubygems.org/gems/xcake/versions/0.9.3) - please give it a few minutes to propagate to the gem registry.

**Comment by pedyard** [comment]
Thanks. It is working as expected now.
