### ISSUE TITLE
Defining subprojects in the Cakefile 

### ISSUE THREAD

**Issue by sergeymild** [igor-makarov/xcake#213]
How generate .xcodeproj for subprojects. For example i have directory called "myProject" in that directory i have project called Main.xcodeproj and also a directory Modules.
In directory modules i have one or two subprojects.
```
myProject/
  Main/
  Main.xcodeproj
  Modules/
    Preferences/
      Preferences/
      Preferences.xcodeproj
    Http
      Http/
      Http.xcodeproj

**Comment by igor-makarov** [comment]
Currently, there's no way to do this with the Cakefile DSL. 

I suggest using separate Cakefiles for each project and putting it in a directory. 

Alternatively, you might wanna look into defining these internal dependencies as local pods through CocoaPods. Whether you're already using CocoaPods or not, they need much less DSL and generate your plists and umbrella headers, and have features that Xcake doesn't have, such as only regenerating the parts that actually changed (incremental install).
