### ISSUE TITLE
Swift packagemanager not working

### ISSUE THREAD

**Issue by PatrickKuijpers** [igor-makarov/xcake#215]
When a package is added using the swift packagemanager, then the new package is removed as soon as I run `xcake make`. Is it not supported by xcake, is it bugged, or am I missing some necessary configuration in the cakefile?

**Comment by igor-makarov** [comment]
Currently, using SwiftPM together with Xcake is not supported. I'd welcome a PR for it though!

**Comment by igor-makarov** [comment]
@PatrickKuijpers I did remember it was somewhat complicated so I checked. Apparently Apple's way of adding SwiftPM packages to an Xcode project is quite cumbersome behind the scenes, and doesn't have a single `Package.swift` that centralizes all the dependencies:

## 1 - Reference the package, similar to the manifest file
```
786816C424AE1C3600FECB42 /* XCRemoteSwiftPackageReference "SnapKit" */ = {
	isa = XCRemoteSwiftPackageReference;
	repositoryURL = "https://github.com/SnapKit/SnapKit";
	requirement = {
		kind = upToNextMajorVersion;
		minimumVersion = 5.0.1;
	};
};
```

## 2 - Create a built package product:
```
786816C524AE1C3600FECB42 /* SnapKit */ = {
	isa = XCSwiftPackageProductDependency;
	package = 786816C424AE1C3600FECB42 /* XCRemoteSwiftPackageReference "SnapKit" */;
	productName = SnapKit;
};
```

## 3 - Create a special file reference unlike any other:

```
786816C624AE1C3600FECB42 /* SnapKit in Frameworks */ = {isa = PBXBuildFile; productRef = 786816C524AE1C3600FECB42 /* SnapKit */; };
```

## 4 - Use the special file reference in the framework build phase:

```
C6A8E264F7297619122A1AE8 /* Frameworks */ = {
	isa = PBXFrameworksBuildPhase;
	buildActionMask = 2147483647;
	files = (
		786816C624AE1C3600FECB42 /* SnapKit in Frameworks */,
		7199C1F72237189779807730 /* Foundation.framework in Frameworks */,
		B64D979A0BF88947BB5EB2C3 /* UIKit.framework in Frameworks */,
	);
	runOnlyForDeploymentPostprocessing = 0;
};
```

**Comment by igor-makarov** [comment]
@PatrickKuijpers so basically to add support for this we are gonna need to:  
1. Figure out what the new DSL syntax in the `Cakefile` should be, if any.
2. Implement the DSL and the intermediate representation.
3. Implement the PBX creator.

**Comment by igor-makarov** [comment]
@PatrickKuijpers keep in mind that the DSL would be repeating **for each package** added and would need to replicate the package requirements syntax.

**Comment by igor-makarov** [comment]
Nerd-sniping does work - @PatrickKuijpers I've managed to figure out a way to do what you were asking for - but not part of Xcake (doesn't seem related). 😂

New gem, called [Xcoed](https://rubygems.org/gems/xcoed/versions/0.0.1) (Xcode-coed) - you create a SwiftPM `Package.swift` file, and it matches it with your project.

In the `Cakefile` you can add it to the `before_save` phase like so:  
```ruby
project.before_save do |project|
  Xcoed::integrate_package_swift! project
end
```

**Comment by igor-makarov** [comment]
@PatrickKuijpers here is the demo app for this Xcoed utility: https://github.com/igor-makarov/DemoXcoed

**Comment by rtjinasjoe** [comment]
@igor-makarov 

Thanks for the demo app!  :)
I only came across this error when running `bundle exec xcake make`

```
{"name"=>"swiftui-navigation-stack", "requirement"=>{"branch"=>["develop"]}, "url"=>"https://github.com/biobeats/swiftui-navigation-stack.git"}
bundler: failed to load command: xcake (/usr/local/bin/xcake)
RuntimeError: Unsupported package requirement `branch`
```

Is it also possible to support other package dependency requirements, such as `revision` and `branch`?

The Package.swift file looks like this:
```
// swift-tools-version:5.1
import PackageDescription

let package = Package(
    name: "PackageName",
    products: [
    ],
    dependencies: [
      .package(
        url: "https://github.com/biobeats/swiftui-navigation-stack.git", from: "0.0.0"),
    ],
    targets: [
        .target(
            name: "TargetName",
            dependencies: [
              "NavigationStack"
            ]
        ),
    ]
)
```

**Comment by igor-makarov** [comment]
Hi @rtjinasjoe! 

I have added the support for `branch` and `revision` requirements.  
Please get the latest Xcoed version [![Gem](https://img.shields.io/gem/v/xcoed.svg)](https://rubygems.org/gems/xcoed).

In the future, make sure to [open an issue on Xcoed](https://github.com/igor-makarov/xcoed/issues/new) repo, so we can discuss it there 💪🏻

**Comment by rtjinasjoe** [comment]
Thanks @igor-makarov for the quick and awesome fix!

> In the future, make sure to [open an issue on Xcoed](https://github.com/igor-makarov/xcoed/issues/new) repo, so we can discuss it there 💪🏻

Will do! :)
