### ISSUE TITLE
UI Test Target Application

### ISSUE THREAD

**Issue by pedyard** [igor-makarov/xcake#216]
After running `xcake make` and creating a UI Testing target, it would seem that the Target Application is never set. Is this a problem with XCake or does this explicitly have to be specified in the Cakefile?

**Comment by igor-makarov** [comment]
Good catch! It's a bug - fixed it now, please update to 0.9.4 💪🏻

**Comment by pedyard** [comment]
Thank you for the quick response. I've updated to 0.9.4, but it doesn't seem to be working. The Target Application is still set to None. The target itself is called ProjectXUITests whereas the product name is ProjectX, if that matters.

**Comment by igor-makarov** [comment]
I'm using it in my own project - the Xcode UI isn't appearing correctly but the tests are running okay.

**Comment by pedyard** [comment]
Ignore that. Even though Target Application is still none, the tests still successfully run, so it's ok.
