### ISSUE TITLE
Not able to Run the Xcode project created by xcake make command, maybe configuration or Executable selection in scheme issue in target.

### ISSUE THREAD

**Issue by Goldy-74** [igor-makarov/xcake#223]
Hi,
I am new in the, Creating Project via CLI,
I tried your CakeFile, [https://github.com/igor-makarov/xcake/blob/main/example/app/CakeMania/Cakefile](url), and by running command `xcake make`, created successfully the Xcode project but the thing is I am not able to run it via Xcode (with run button or Command + R), I think some issue is in the configuration in the project target(Please see the attached image).
Please help me out in this, I am having my all hope in this tool and every one in my organisation is depending on me and I am depending on this tool :p

<img width="932" alt="Screenshot 2022-02-23 at 9 01 17 PM" src="https://user-images.githubusercontent.com/19763106/155351489-9dbd9832-c907-40f9-8594-c39dc9c9889c.png">
<img width="943" alt="Screenshot 2022-02-23 at 9 38 53 PM" src="https://user-images.githubusercontent.com/19763106/155360226-e567a002-9479-4b98-8dd1-e804e36e8b20.png">
<img width="936" alt="Screenshot 2022-02-23 at 9 38 38 PM" src="https://user-images.githubusercontent.com/19763106/155360242-f0328d26-c0c5-4e86-9502-0cf947a52ec9.png">

**Comment by igor-makarov** [comment]
From your screenshots, it looks like you need to select the executable in your scheme to run it. Can you try that and see if it helps?

**Comment by Goldy-74** [comment]
@igor-makarov , I know and It worked, but what I need without opening Xcode it should work. just from the command line.
`xcake make`
How It can be done? any suggestion, I have already used the sample project that also require the same approach for selecting excutable from scheme.

**Comment by igor-makarov** [comment]
I'm gonna be releasing new version with fix shortly.

**Comment by igor-makarov** [comment]
New version with fix available: [xcake 0.12.1](https://rubygems.org/gems/xcake/versions/0.12.1)
