### ISSUE TITLE
.intentdefinition files misclassified as resources. 

### ISSUE THREAD

**Issue by nicolasrostan** [igor-makarov/xcake#228]
Intent definition files (https://developer.apple.com/documentation/widgetkit/making-a-configurable-widget) are being classified as resources, when they should be classified as sources.

Suggested solution:
add .intentdefinition to the sources list in [path_classifier](https://github.com/igor-makarov/xcake/blob/66486c8e0df592a75db6902bec0df41c4b3de6d8/lib/xcake/path_classifier.rb#L10)

**Comment by CaioSym** [comment]
Any updates on this @igor-makarov ?

**Comment by CaioSym** [comment]
Nah. Thanks for all the good work. GH Notifications are crap 😂
