### ISSUE TITLE
“YourApp.app” couldn’t be opened because you don’t have permission to view it

### ISSUE THREAD

**Issue by gimenete** [igor-makarov/xcake#46]
I'm trying to use xcake. First problem I had was the Info.plist file missing. But I already fixed that copying a very basic Info.plist file from other app (I checked it and has nothing special).

Now I have this error when trying to run the app:

> The file “YourApp.app” couldn’t be opened because you don’t have permission to view it.

I'm using XCode 7.2 (7C68) and the Cakefile is pretty much the default one (only adding some source files). I'm attaching a screenshot of the navigation bar.

<img width="432" alt="screen shot 2016-02-03 at 5 29 37 pm" src="https://cloud.githubusercontent.com/assets/50486/12788967/1bae3b3e-ca9c-11e5-8b3c-6709f218dcbe.png">

In the beginning I thought was a permission problem with the generated .app file. But if I right-click on the `YourApp.` file to show it in finder it doesn't open the directory where it is, so I guess the file is bascially missing. It is strange to me the name of the file. It doesn't end in `.app`, just in a dot.

Am I missing some step?

Thanks,

**Comment by jcampbell05** [comment]
Interesting, it could be that Xcode is unable to find your project. Could you zip it up and send it to james@supmenow.com I'll take a look :)

**Comment by gimenete** [comment]
Well, you know what? Before sending you the zip I wanted to check everything again. And... now it works. I checked and I had the same problem again. But I zipped the directory, unzipped it again (removing the previous directory first) and voilá, now it works. After making more tests I was able to reproduce the problem again but I run `xcake make` and then it worked, and I haven't found a way to re-reproduce it.

So I'm closing this and I'll let you know if I find exactly when this happens. Thanks!

**Comment by jcampbell05** [comment]
Thank you :) let me know if it happens again.

**Comment by chinastate** [comment]
I have the same problem on Xcode it says, "The file “morpher app soundboard.app” couldn’t be opened because you don’t have permission to view it."  what could I do to fix this problem?

**Comment by jcampbell05** [comment]
@chinastate if you are able to send me the project then maybe I can investigate. I'm currently not sure what causes this problem so can't provide a work around.

**Comment by chinastate** [comment]
What's your email

**Comment by jcampbell05** [comment]
jscampbell.05@googlemail.com

**Comment by chinastate** [comment]
Did you get my project in an email from me yet

**Comment by jcampbell05** [comment]
yes I got it having a look :)

**Comment by chinastate** [comment]
The error I'm having is this

**Comment by chinastate** [comment]
How far have you gotten on my project errors

**Comment by chinastate** [comment]
How are you doing with the code

**Comment by chinastate** [comment]
?

**Comment by jcampbell05** [comment]
@chinastate still trying to reproduce :)

**Comment by chinastate** [comment]
What do you mean by reproduce

**Comment by chinastate** [comment]
Now I get this error

**Comment by ashikurrahmanrobin** [comment]
I also face this error please help me 
![screenshot 2019-02-09 at 10 43 56 pm](https://user-images.githubusercontent.com/16266135/52530082-787edd80-2d29-11e9-958f-dc9ff0f37911.png)

**Comment by jcampbell05** [comment]
@ashikurrahmanrobin can you provide the steps you did to encounter this error and can you zip your project file and cakefile here so we can take a look.
